// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartMaintenance.Infrastructure.Persistence;

#nullable disable

namespace SmartMaintenance.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260910014017_AddIotAlertsAndPredictionFlags")]
    partial class AddIotAlertsAndPredictionFlags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartMaintenance.Domain.Entities.AiPrediction", b =>
                {
                    b.Property<int>("PredictionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PredictionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PredictionId"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("AssetID");

                    b.Property<bool>("BasedOnSampleData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("PredictedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PredictionId");

                    b.HasIndex("AssetId", "PredictedAt");

                    b.ToTable("AI_PREDICTIONS", null, t =>
                        {
                            t.HasCheckConstraint("CK_AIPREDICTIONS_Risk", "[RiskLevel] IN ('Low', 'Medium', 'High')");
                        });
                });

            modelBuilder.Entity("SmartMaintenance.Domain.Entities.Asset", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AssetID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MaintenanceRisk")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AssetId");

                    b.ToTable("ASSETS", null, t =>
                        {
                            t.HasCheckConstraint("CK_ASSETS_Status", "[Status] IN ('Operational', 'Warning', 'Maintenance', 'Out of Service')");

                            t.HasCheckConstraint("CK_ASSETS_Type", "[Type] IN ('Wi-Fi', 'Air Conditioner', 'Projector', 'Light', 'Fan')");
                        });
                });

            modelBuilder.Entity("SmartMaintenance.Domain.Entities.IotAlert", b =>
                {
                    b.Property<int>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AlertID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlertId"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("AssetID");

                    b.Property<int>("DataId")
                        .HasColumnType("int")
                        .HasColumnName("DataID");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("ReadingValue")
                        .HasColumnType("float");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("Threshold")
                        .HasColumnType("float");

                    b.HasKey("AlertId");

                    b.HasIndex("AssetId", "DetectedAt");

                    b.ToTable("IOT_ALERTS", null, t =>
                        {
                            t.HasCheckConstraint("CK_IOTALERTS_Severity", "[Severity] IN ('Low', 'Medium', 'High')");
                        });
                });

            modelBuilder.Entity("SmartMaintenance.Domain.Entities.IotData", b =>
                {
                    b.Property<int>("DataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DataID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DataId"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("DeviceID");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("ReadingValue")
                        .HasColumnType("float");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("DataId");

                    b.HasIndex("DeviceId", "Timestamp");

                    b.ToTable("IOT_DATA", null, t =>
                        {
                            t.HasCheckConstraint("CK_IOTDATA_MetricType", "[MetricType] IN ('temperature', 'humidity', 'power_status')");
                        });
                });

            modelBuilder.Entity("SmartMaintenance.Domain.Entities.IotDevice", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DeviceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceId"));

                    b.Property<string>("DeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DeviceId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("IOT_DEVICES", (string)null);
                });

            modelBuilder.Entity("SmartMaintenance.Domain.Entities.IotMapping", b =>
                {
                    b.Property<int>("MappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MappingId"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("AssetID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("DeviceID");

                    b.HasKey("MappingId");

                    b.HasIndex("AssetId")
                        .IsUnique();

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("IOT_MAPPINGS", (string)null);
                });

            modelBuilder.Entity("SmartMaintenance.Domain.Entities.MaintenanceHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HistoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("AssetID");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("WorkOrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.HasKey("HistoryId");

                    b.ToTable("MAINTENANCE_HISTORY", (string)null);
                });

            modelBuilder.Entity("SmartMaintenance.Domain.Entities.MaintenanceRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RequestID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<int?>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("AssetID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RequesterId")
                        .HasColumnType("int")
                        .HasColumnName("RequesterID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RequestId");

                    b.ToTable("MAINTENANCE_REQUESTS", null, t =>
                        {
                            t.HasCheckConstraint("CK_REQUESTS_Status", "[Status] IN ('Submitted', 'Pending', 'In Progress', 'Resolved', 'Closed', 'Rejected')");
                        });
                });

            modelBuilder.Entity("SmartMaintenance.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("USERS", (string)null);
                });

            modelBuilder.Entity("SmartMaintenance.Domain.Entities.WorkOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("AssetID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("RequestID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TechnicianId")
                        .HasColumnType("int")
                        .HasColumnName("TechnicianID");

                    b.HasKey("OrderId");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("WORK_ORDERS", null, t =>
                        {
                            t.HasCheckConstraint("CK_WORKORDERS_Status", "[Status] IN ('Assigned', 'In Progress', 'Completed', 'Cancelled')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
